[workspace]
members = ["src/flux", "src/libstd", "src/infer"]

# https://rustwasm.github.io/docs/book/reference/code-size.html#optimizing-builds-for-code-size
[profile.release]
lto = true
opt-level = 'z'
